version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/payload-react-blog

hooks:
  ApplicationStop:
    - location: scripts/app-stop.sh
      timeout: 300

  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300

  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/app-start.sh
      timeout: 300